import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const startParam = searchParams.get('start');
    const endParam = searchParams.get('end');

    const now = new Date();
    
    // Default endDate to end of today
    const endDate = endParam ? new Date(endParam) : new Date();
    endDate.setHours(23, 59, 59, 999);

    // Default startDate to YTD (Jan 1st of current year)
    const startDate = startParam ? new Date(startParam) : new Date(now.getFullYear(), 0, 1);
    startDate.setHours(0, 0, 0, 0);

    let daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 3600 * 24));
    daysDiff = Math.min(Math.max(daysDiff, 1), 365); 

    // Find teachers who signed up precisely within the date range (Base Cohort)
    const cohortTeachers = await prisma.teacher.findMany({
      where: { 
        createdAt: { gte: startDate, lte: endDate } 
      },
      include: {
        lessons: { select: { createdAt: true } },
        quizzes: { select: { createdAt: true } },
        assessments: { select: { createdAt: true } }
      }
    });

    const totalCohort = cohortTeachers.length;
    let retainedCount = 0;
    
    // Track volume of stuff generated by this specific cohort broadly
    const artifactFrequency: Record<string, number> = {
      '0': 0,
      '1': 0,
      '2-5': 0,
      '6-10': 0,
      '11+': 0
    };

    const timeseriesData: Record<string, { newUsers: number, retainedUsers: number }> = {};
    
    // Chart tracks data on a per-cohort-day basis
    for (let i = 0; i <= daysDiff; i++) {
       const d = new Date(startDate);
       d.setDate(d.getDate() + i);
       if (d > endDate) break;
       const key = d.toISOString().split('T')[0];
       timeseriesData[key] = { newUsers: 0, retainedUsers: 0 };
    }

    cohortTeachers.forEach(teacher => {
      const signupDateStr = teacher.createdAt.toISOString().split('T')[0];
      
      const artifacts = [
        ...teacher.lessons.map(l => l.createdAt),
        ...teacher.quizzes.map(q => q.createdAt),
        ...teacher.assessments.map(a => a.createdAt)
      ];

      const count = artifacts.length;
      if (count === 0) artifactFrequency['0']++;
      else if (count === 1) artifactFrequency['1']++;
      else if (count <= 5) artifactFrequency['2-5']++;
      else if (count <= 10) artifactFrequency['6-10']++;
      else artifactFrequency['11+']++;

      let isRetained = false;
      artifacts.forEach(date => {
        const artDateStr = date.toISOString().split('T')[0];
        // Retained strictly if generating anything AFTER the calendar day they signed up
        if (artDateStr > signupDateStr) {
            isRetained = true;
        }
      });

      // Update timeseries mapping based on the day they signed up
      if (timeseriesData[signupDateStr]) {
          timeseriesData[signupDateStr].newUsers++;
          if (isRetained) {
              timeseriesData[signupDateStr].retainedUsers++;
          }
      }

      if (isRetained) retainedCount++;
    });

    const retentionRate = totalCohort === 0 ? 0 : (retainedCount / totalCohort) * 100;

    const chartData = Object.keys(timeseriesData).map(k => ({
      date: k,
      newUsers: timeseriesData[k].newUsers,
      retainedUsers: timeseriesData[k].retainedUsers
    }));

    const frequencyData = Object.keys(artifactFrequency).map(k => ({
      range: k,
      users: artifactFrequency[k]
    }));

    return NextResponse.json({
      success: true,
      data: {
        totalCohort,
        retainedCount,
        retentionRate,
        frequencyData,
        chartData,
        startDate: startDate.toISOString().split('T')[0],
        endDate: endDate.toISOString().split('T')[0]
      }
    });

  } catch (error) {
    console.error('Retention stats error:', error);
    return NextResponse.json({ success: false, error: 'Failed to fetch retention stats' }, { status: 500 });
  }
}
